### ISSUE TITLE
User can add a public event

### ISSUE THREAD

**Issue by mhulet** [extinctionrebellion/RebelsManager#115]
This is a very first iteration to have events ready soon and gather initial feedback from coordinators.

* An event has a name and description (no wysiwyg for now), a start and end datetime, a link to a Facebook event. All fields except Facebook event URL are mandatory.
* An event can belong to a local group (optional, as it may be a national event)
* All events are reachable from an _Events_ link in the top bar
* No images for now

For datetimes, we have the branch timezone set in `ENV['XR_BRANCH_TIMEZONE']`. I can take care of date and time pickers (I have code I can use from another project), just set them up as `:text` fields for now.

![XR - 26](https://user-images.githubusercontent.com/293355/70223344-de6ea280-174b-11ea-9293-7cd148638352.png)

**Comment by begault** [comment]
@mhulet I can take it :) I've some free time these days

**Comment by mhulet** [comment]
@begault Awesome! I'll reply to your email and will do my best to shape this section (events) up asap.

**Comment by begault** [comment]
@mhulet  Concerning the date fields, do we really need text format or a string is ok ? 
If you give me the link of a gem you want to use, I can do it directly. If it's a private code, i'll let you manage it :)

**Comment by mhulet** [comment]
> Concerning the date fields, do we really need text format or a string is ok ?
Oh sorry @begault, yes `:string` not `:text`.

**Comment by mhulet** [comment]
> If you give me the link of a gem you want to use, I can do it directly. If it's a private code, i'll let you manage it :)

That's on a private repository, I'll have fun with it once this is ready.
