### ISSUE TITLE
User can set rebel availability for XR

### ISSUE THREAD

**Issue by mhulet** [extinctionrebellion/RebelsManager#14]
String input.
Could be an exact number of hours or include details.

- [ ] Create `rebel.availability` (migration, string attribute)
- [ ] Add field to `manage/rebels/_form`
- [ ] Add attribute to rebels_params on `Manager::RebelsController`

**Comment by jbehrens94** [comment]
Is this availability related to a certain unit, or just something like a status text? I'd like to pick this one up, by the way, can you assign it to me?

**Comment by mhulet** [comment]
> @mhulet Is this availability related to a certain unit (2 hours a day), or just something like a status text ("I'm available 2 hours a day")?

Good question - let's think a bit about it.

* Most people will not be able to say _"I'm available X hours/day"_, week, month or so - that's why I was thinking about having a free text field
* But yet, we will not be able to really use this data (and people will reply in different languages, at least in Belgium).
* So maybe a good option could be a dropdown like:

- I am currently unavailable, you have all my support! (value: `unavailable`)
- A few hours a month (value: `few_hours_a_month`)
- A couple of hours a week (value: `few_hours_a_week`)
- More than 10 hours a week (value: `10_hours_a_week`)

* This allows to add new options later.
* This allows to filter rebels: for example let's find all rebels around a specific location with a few hours a week availability and suggest them a specific project

WDYT @jbehrens94 ?

**Comment by jbehrens94** [comment]
Good idea, @mhulet! I'll see if I have time today to work on it and make a PR. 👍

**Comment by jbehrens94** [comment]
@mhulet Maybe you can help me out, I'm trying to run the project locally with `docker-compose up` but that doesn't seem to do the trick, could you give a description on how to get it running locally? :)

**Comment by mhulet** [comment]
Good question... This was my first project on a Docker container and I don't use the container anymore. It would be great if we had someone who knows about Docker who could review the setup and write a small guide in the README.

@jbehrens94 which OS are you running?

**Comment by mhulet** [comment]
I have installed Docker Desktop for Mac on a fresh laptop. Once done, I have `docker-compose` available.

Then, in the project directory:

```
$ docker-compose up -d
```

It takes some time on the first run, and it fails while creating the `web` container. I `up` again and all seems good but I see this error: `HTTP parse error, malformed request`.

I will take time to investigate. Do you have the same error on your side?

**Comment by jbehrens94** [comment]
@mhulet When I run `docker-compose up -d` I get a live `rebelsmanager_pg_1` and `rebelsmanager_webpacker_1` container running, but `spring_1` and `web_1` fail somehow and are stopped directly.

**Comment by jbehrens94** [comment]
Alright, when I removed `/tmp` that fixes booting the server, but I'm not sure how I should pass the required postgres credentials. Do I pass them like `docker-compose up -d -e POSTGRES_HOST=...` and if so, what should the host be? When I'm trying to run `rails db:create` in `web_1` it's not finding PostgreSQL because it's looking at localhost:5432.

**Comment by jbehrens94** [comment]
After #77 got merged, we can close this issue. 👍
