### ISSUE TITLE
A rebel can be marked as regular volunteer

### ISSUE THREAD

**Issue by mhulet** [extinctionrebellion/RebelsManager#141]
**Is your feature request related to a problem? Please describe.**
XR International Support Team wants to know how many regular volunteers are involved for each national group. Each group will provide this number by hand and we could make it easier.

**Describe the solution you'd like**
A rebel can be edited and marked as _"Regular volunteer"_. This is an organizer role.

**Describe alternatives you've considered**
Having a list of volunteers on a sheet of papyrus paper.

**Additional context**
New attribute: `rebel.regular_volunteer`.
New checkbox on `rebels#edit` form (not the public one, only on the admin side).
The checkbox is only available to national coordinators (`user.admin?`)

**Comment by aki1221** [comment]
can i pick this @mhulet

**Comment by Systho** [comment]
I'd like to take this issue as a first step into the project.

What is the strategy about automated testing ?
What about changelog amendment and version number ?
