### ISSUE TITLE
Please add details to XR Tech Project Directory

### ISSUE THREAD

**Issue by cowtrix** [extinctionrebellion/RebelsManager#165]
Hello all,

Please would someone fill in the appropriate details on the XR Tech Directory post found here: https://base.organise.earth/t/tech-project-directory/1100

If you don't have access to the XR Base, please email me at seandgfinnegan@gmail.com

The information template looks like this:

# Project Name

| Project Owner: | John Smith | john@protonmail.com | @johnsmith |
|-|-|-|-|

*Date Updated: 28/1/2020*

### Containing Working Group

E.g. XR Germany Tech Team

### Brief

A 100-word max description of the project. Try to be succinct and non-technical. The elevator pitch you'd give to a relatively experienced, but non-technical Rebel.

### Project Status

Ongoing. Link to meeting minutes if you wish or other source of updates.

### Important Links

| [Specification Document](http://notareallink.org) | [Mattermost Channel](http://notareallink.org) | [Discourse Thread](http://notareallink.org) | [Live Site](http://notareallink.org) |
|-|-|-|-|

**Comment by mhulet** [comment]
@cowtrix Thanks for the heads-up! Have added details on the XR Tech Directory.
