### ISSUE TITLE
Calls to the Mailtrain API run as background jobs

### ISSUE THREAD

**Issue by mhulet** [extinctionrebellion/RebelsManager#31]

**Comment by aki1221** [comment]
Hey, @mhulet  can I pick up this or are there any other tickets available?.

**Comment by mhulet** [comment]
Hey @aki1221 thanks a lot for your message 👍I have been away for a few days. Could you send me an email at jahmali@protonmail.com so that I share with you a Mattermost channel where it will be easier to communicate together?

**Comment by mhulet** [comment]
Released with https://github.com/extinctionrebellion/RebelsManager/pull/105
