### ISSUE TITLE
Admin can delete a local group if it has no rebel anymore

### ISSUE THREAD

**Issue by mhulet** [extinctionrebellion/RebelsManager#43]
* Only an admin (`current_user.admin?`) can delete a local group
* 'Delete' button is shown only to admin users
* `services/local_groups/delete_service.rb` checks that there is no rebel anymore

**Comment by lucianolima00** [comment]
Hey @mhulet, I'd like to do this issue

**Comment by mhulet** [comment]
Done: https://github.com/extinctionrebellion/RebelsManager/pull/46
