### ISSUE TITLE
User can view/set the # of arrests for a rebel

### ISSUE THREAD

**Issue by mhulet** [extinctionrebellion/RebelsManager#7]

**Comment by kvrag** [comment]
Hi there. Would love to look into this issue for Hacktober. Looks like the bare bones are:
 - add a # of arrests column to Rebel model
 - add form field to the Rebel edit page for # of arrests
 - show the # of arrests on Rebel show page

Any other instructions / specific things I should build into that?

**Comment by mhulet** [comment]
Hi @kvrag, thanks a lot for your interest - just added the Hacktoberfest label 🙌

That's all correct. I would also add this:

* add the # of arrests as a column on [the Rebels table](https://github.com/extinctionrebellion/RebelsManager/blob/master/app/views/rebels/index.html.slim#L19), available in exports and for being able to sort the table on arrests
