### ISSUE TITLE
Rebel can be added to working groups when created by a local group coordinator

### ISSUE THREAD

**Issue by mhulet** [extinctionrebellion/RebelsManager#86]
The current form (`/rebels/new`) doesn't allow to add the rebel to working groups directly, because working groups are local group-specific. User has to create the rebel, then edit it.

When the action is done by a local group coordinator (`!user.local_group.nil?`), the local group is defined and we can show working groups for this local group.

- add the Working Groups section to the form, showing working groups for this local group
- make sure that `Rebels::CreateService` is updated accordingly (params)

**Comment by gr1d99** [comment]
Hey @mhulet, I am interested with this issue, can I work on it?

**Comment by mhulet** [comment]
Sure, thanks a lot! I’m on my phone, will assign issue later, but you can
definitely start it.

**Comment by gr1d99** [comment]
This issue can now be closed @mhulet
