### ISSUE TITLE
Email addresses are encrypted in the database

### ISSUE THREAD

**Issue by mhulet** [extinctionrebellion/RebelsManager#9]

**Comment by begault** [comment]
Helo 👋 
Depending on what service is used to run the server(s), this migth be a good proposition: https://github.com/ankane/lockbox
Do you have more details about this issue @mhulet ?

**Comment by mhulet** [comment]
Yes @begault, I had a bookmark to this one too: https://ankane.org/sensitive-data-rails

We are currently running the RM on Heroku, and will move the PostgreSQL database to our branch server as soon as I find someone who can take the time to manage this.

What we want is - at least - to make sure that getting a copy of the database doesn't expose email addresses (and [phone numbers](https://github.com/extinctionrebellion/RebelsManager/issues/8)).

Lockbox seems to be an easy way to do it the right way.

This would be awesome to have someone working on this sensitive issue.

**Comment by begault** [comment]
Thanks for the details @mhulet  
I can take this one as a first contribution :) 
Can I use it for Hacktoberfest ? 
I'll expose my thought about the implementation here before development.
